# Generated by Django 4.0 on 2022-05-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='particpants',
            new_name='participants',
        ),
    ]
