# Generated by Django 4.0 on 2022-05-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_particpants_room_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
